# Generated by Django 5.0.13 on 2025-04-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'verbose_name': 'собакевич', 'verbose_name_plural': 'dogs'},
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100, verbose_name='breed'),
        ),
    ]
