# Generated by Django 5.0.13 on 2025-04-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_alter_dog_options_alter_breed_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'verbose_name': 'собака', 'verbose_name_plural': 'собаки'},
        ),
    ]
