# Generated by Django 5.0.13 on 2025-04-13 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_alter_dog_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='хозяин'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='birth date'),
        ),
    ]
