# Generated by Django 5.0.13 on 2025-04-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_dog_owner_alter_dog_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Кличка родителя')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения родителя')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.breed', verbose_name='Порода родителя')),
                ('dogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dog')),
            ],
            options={
                'verbose_name': 'parent',
                'verbose_name_plural': 'parents',
            },
        ),
    ]
