# Generated by Django 5.0.13 on 2025-04-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_alter_dog_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='views',
            field=models.ImageField(default=0, upload_to='', verbose_name='Просмотры'),
        ),
    ]
